spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
    url: jdbc:mariadb://localhost:3306/sbb__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true